version: "3.3"
services:
  spark-jupyter:
    image: jupyter/all-spark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/taian/work
    container_name: spark-jupyter
    user: root
    environment:
      - NB_USER=taian
      - CHOWN_HOME=yes
      - CHOWN_EXTRA_OPTS='-R'
      - PYARROW_IGNORE_TIMEZONE=1
      - JUPYTER_TOKEN=123qwe
      - PASSWORD=123qwe
    working_dir: /home/taian/work
